import {
  Server,
  Database,
  Shield,
  Scale,
  Cloud,
  Code,
  FileJson,
  Zap,
  GitBranch,
  LineChart,
  BarChart,
  Layers,
  Bot,
  Bell,
  Users,
  MessageSquare,
  Heart,
  Clock,
  Boxes,
  CircuitBoard,
  Gauge,
  Timer,
  Workflow,
  Lock,
  Globe,
  Box,
  Settings,
  Command,
  Search,
  Share2,
  History,
} from "lucide-react";
import {
  ServiceBenefit,
  ServiceCategoryData,
  ServiceCategory,
  ServiceProcessStep,
} from "@/types/service";
import Routes from "@/constants/routes";

const backendBenefits: ServiceBenefit[] = [
  { key: "scalable-architecture", icon: Scale },
  { key: "optimized-database", icon: Database },
  { key: "robust-infrastructure", icon: Server },
  { key: "advanced-security", icon: Shield },
];

const backendProcessList: ServiceProcessStep[] = [
  { key: "needs-analysis" },
  { key: "system-design" },
  { key: "api-development" },
  { key: "database" },
  { key: "testing-security" },
  { key: "deployment-monitoring" },
];

const backendCategory: ServiceCategoryData = {
  id: ServiceCategory.BACKEND,
  icon: Server,
  benefits: backendBenefits,
  processList: backendProcessList,
  subServices: [
    {
      id: "api",
      route: Routes.service.backend.api,
      icon: Code,
      features: [
        { key: "rest-graphql", icon: Code },
        { key: "advanced-security", icon: Shield },
        { key: "optimal-performance", icon: Zap },
        { key: "complete-documentation", icon: FileJson },
      ],
      benefits: [
        { key: "high-availability", icon: Cloud },
        { key: "scalability", icon: GitBranch },
        { key: "advanced-monitoring", icon: LineChart },
        { key: "intelligent-cache", icon: Zap },
      ],
      faqItems: [
        { key: "rest-vs-graphql" },
        { key: "api-security" },
        { key: "scaling" },
        { key: "documentation" },
        { key: "post-deployment-support" },
      ],
      testimonials: [],
      complementaryServices: [
        { key: "advanced-analytics", icon: BarChart },
        { key: "data-migration", icon: Database },
        { key: "integration", icon: Layers },
      ],
    },
    {
      id: "database",
      route: Routes.service.backend.database,
      icon: Database,
      features: [
        { key: "optimized-architecture", icon: Database },
        { key: "enhanced-security", icon: Shield },
        { key: "high-performance", icon: Zap },
        { key: "backup-recovery", icon: History },
      ],
      benefits: [
        { key: "horizontal-scalability", icon: GitBranch },
        { key: "replication", icon: Share2 },
        { key: "advanced-monitoring", icon: LineChart },
        { key: "optimized-search", icon: Search },
      ],
      faqItems: [
        { key: "sql-vs-nosql" },
        { key: "data-security" },
        { key: "performance-optimization" },
        { key: "migration-services" },
        { key: "data-availability" },
      ],
      testimonials: [],
      complementaryServices: [
        { key: "data-migration", icon: Cloud },
        { key: "audit-optimization", icon: BarChart },
        { key: "monitoring-24-7", icon: Timer },
      ],
    },
    {
      id: "bots",
      route: Routes.service.backend.bots,
      icon: Bot,
      features: [
        { key: "discord-slack", icon: MessageSquare },
        { key: "advanced-commands", icon: Command },
        { key: "optimal-performance", icon: Zap },
        { key: "integrations", icon: Settings },
      ],
      benefits: [
        { key: "intelligent-moderation", icon: Shield },
        { key: "notifications", icon: Bell },
        { key: "engagement", icon: Users },
        { key: "statistics", icon: LineChart },
      ],
      faqItems: [
        { key: "bot-types" },
        { key: "bot-reliability" },
        { key: "customization" },
        { key: "security" },
        { key: "post-deployment-support" },
      ],
      testimonials: [],
      complementaryServices: [
        { key: "analytics", icon: BarChart },
        { key: "support-24-7", icon: Clock },
        { key: "evolutions", icon: Heart },
      ],
    },
    {
      id: "microservices",
      route: Routes.service.backend.microservices,
      icon: Box,
      features: [
        { key: "scalable-architecture", icon: Boxes },
        { key: "continuous-deployment", icon: GitBranch },
        { key: "optimal-performance", icon: Zap },
        { key: "high-availability", icon: Shield },
      ],
      benefits: [
        { key: "granular-scalability", icon: Scale },
        { key: "flexible-deployment", icon: Cloud },
        { key: "fault-isolation", icon: CircuitBoard },
        { key: "advanced-monitoring", icon: LineChart },
      ],
      faqItems: [
        { key: "when-microservices" },
        { key: "service-communication" },
        { key: "data-consistency" },
        { key: "infrastructure-monitoring" },
        { key: "team-training" },
      ],
      testimonials: [],
      complementaryServices: [
        { key: "devops-cicd", icon: Workflow },
        { key: "monitoring-24-7", icon: Timer },
        { key: "optimization", icon: Gauge },
      ],
    },
    {
      id: "cloud",
      route: Routes.service.backend.cloud,
      icon: Cloud,
      features: [
        { key: "multi-cloud", icon: Cloud },
        { key: "advanced-security", icon: Shield },
        { key: "optimal-performance", icon: Zap },
        { key: "automatic-scalability", icon: Scale },
      ],
      benefits: [
        { key: "high-availability", icon: Server },
        { key: "elastic-storage", icon: Database },
        { key: "advanced-monitoring", icon: LineChart },
        { key: "enhanced-security", icon: Lock },
      ],
      faqItems: [
        { key: "platform-choice" },
        { key: "cloud-security" },
        { key: "cost-optimization" },
        { key: "high-availability" },
        { key: "support-24-7" },
      ],
      testimonials: [],
      complementaryServices: [
        { key: "cloud-migration", icon: GitBranch },
        { key: "multi-region", icon: Globe },
        { key: "devops", icon: Timer },
      ],
    },
  ],
};

export default backendCategory;
